### ISSUE TITLE
Github is a community for unobfuscated code.

### ISSUE THREAD

**Issue by VillainsRule4000** [Jude-Gideon/Blooket#12]
This platform is a platform for files where users can learn from code.
It isn't a place to mash it up.

**Comment by Jude-Gideon** [comment]
I see you on no other obfuscated Blooket hack repos, the point is to show off code you made, if I don't want it stolen and I only want people to use it because I am capable of maintaining it then I will make that choice.

**Comment by VillainsRule4000** [comment]
A mashed up list of numbers and letters isn't "showing it off".
You can't trust code, it can do a lot of bad things.
While you don't want it to be stolen, I don't know you're not stealing it from others.
As you have a similar name to lol-jude, who stole the code of gliz, I chose to make this issue and question this repository.

Stolen code can be reported to Github, who will quickly take care of the issue.

Well, actually, I chose to question this after I found how your [9 day old] site had stolen the entire CSS from @notzastix's [months old] site.

**Comment by Jude-Gideon** [comment]
I understand where you come from when saying I may steal my code but I make it all myself, if you look at closed issues it's clear I have the source code and the capability to maintain. I remember the whole lol-jude thing but I can remind, that Jude is just a name many people share it, as for the CSS file, I was testing a website downloader and seeing if it was easily modifiable, it has been taken down, I do not have any malicious code in my hacks, they all work and the only bad thing that can happen is getting banned.

**Comment by Jude-Gideon** [comment]
Plus one of the only unobfuscated hacks on this platform being from the fake Gliz don't work in any form.

**Comment by rand0mdeveloper** [comment]
I don't want to be a leach and hop onto your issues Jude but I would like to add I personally know Jude and he was not Lol-Jude, he used to own the account [Jvdz3](https://github.com/Jvdz3) but it got hacked because it had pro, the school developer pack expired on the account so the hacker has a worthless account, but I can assure you Mr. Villians Rule that Jude makes all of his hacks, I have contributed to some but prefer to have my name left out, I have access to the source repo, and as I said I have written some hacks fully.

**Comment by rand0mdeveloper** [comment]
If you have any more question contact me on Discord
Random Developer#1111

**Comment by notzastix** [comment]
lol-jude just skidded from gliz

**Comment by notzastix** [comment]
> A mashed up list of numbers and letters isn't "showing it off". You can't trust code, it can do a lot of bad things. While you don't want it to be stolen, I don't know you're not stealing it from others. As you have a similar name to lol-jude, who stole the code of gliz, I chose to make this issue and question this repository.
> 
> Stolen code can be reported to Github, who will quickly take care of the issue.
> 
> Well, actually, I chose to question this after I found how your [9 day old] site had stolen the entire CSS from @notzastix's [months old] site.

LOL

**Comment by notahumans-official** [comment]
Actually, there is a difference. I tried both. Jude works, but the other dude's does not. Also, Jude is a common name, so that part is likely a coincidence.🙄

**Comment by notahumans-official** [comment]
> If you have any more question contact me on Discord Random Developer#1111

Also, it wasn't wise to POST YOUR DISCORD DATA.

**Comment by notzastix** [comment]
> > If you have any more question contact me on Discord Random Developer#1111
> 
> Also, it wasn't wise to POST YOUR DISCORD DATA.

its just his discord discrim? not like we can do anything but send him a friend request or a message.

**Comment by Jude-Gideon** [comment]
Yeah, its just a Discord name plus he changed it.

**Comment by Jude-Gideon** [comment]
> lol-jude just skidded from gliz

Yeah I know, thats why I was nervous to make hacks due to getting confused with loser who can't code lol.

**Comment by Jude-Gideon** [comment]
If you care his name is now
sparky#9999

**Comment by notzastix** [comment]
might wanna actually learn how to make scripts for react sites before making them.

![image](https://user-images.githubusercontent.com/69748767/198748229-d39e2072-46b1-4a57-b5b2-789ce43f00d2.png)

**Comment by notzastix** [comment]
i wonder why this is so similar to gliz's old footer

gliz's:
![image](https://user-images.githubusercontent.com/69748767/198748442-2d5a7974-9a8e-4cf5-8133-dd965629b429.png)

yours:
![image](https://user-images.githubusercontent.com/69748767/198748461-44f823bb-877c-4841-a145-d8559f128182.png)

**Comment by notzastix** [comment]
love how similar your footer function is to gliz's

gliz's:
![image](https://user-images.githubusercontent.com/69748767/198748678-8d02991d-8ded-4025-81fa-809e9e0222f2.png)

your's:
![image](https://user-images.githubusercontent.com/69748767/198748689-f3fae8e8-1290-4b77-9b79-bf20893a60b5.png)

**Comment by Jude-Gideon** [comment]
Other people use it i can change it if it's an issue.

**Comment by notzastix** [comment]
> Other people use it i can change it if it's an issue.

thats not the point, you should make your own or just do an alert, you shouldnt just copy directly what gliz did.

**Comment by VillainsRule4000** [comment]
goofy ahh react methods :skull:

**Comment by Jude-Gideon** [comment]
When I'm home again ill do something I guess.

**Comment by notzastix** [comment]
alright

**Comment by Jude-Gideon** [comment]
> goofy ahh react methods :skull:

Yeah, codes shittlity wrote bit still works

**Comment by Jude-Gideon** [comment]
> alright

I'm not home until Monday though, I'll either change the footer to be different from Gliz, or just make something like an alert.

**Comment by notahumans-official** [comment]
> If you care his name is now sparky#9999

I was just pointing out that you shouldn't post that kind of stuff on a public forum, I'm not too concerned...

**Comment by jood112** [comment]
it doesnt matter if the code is obfuscated or not they can keep it the way they want

also if you really want deobsucated code learn how do deobfuscate it yourself dont complain about it
