### ISSUE TITLE
Contest of Candy.

### ISSUE THREAD

**Issue by notahumans-official** [Jude-Gideon/Blooket#15]
The global contest of candy event is tomorrow, and I plan to use cheats on it. Will they work, you think? (I want the prize so bad!)

**Comment by Jude-Gideon** [comment]
The only hack that doesn't work is the chestESP because of the drawing elements, all other hacks work.

**Comment by Jayden7480** [comment]
wdym the hacks dont work and the coc is ending tmrw HELP US BY FIXING THIS

**Comment by Jude-Gideon** [comment]
> wdym the hacks dont work and the coc is ending tmrw HELP US BY FIXING THIS

The hacks work fine.

**Comment by notahumans-official** [comment]
it was on ben's site. blooket apis would not work ;-;
