### ISSUE TITLE
It aint working no more

### ISSUE THREAD

**Issue by Shensinwu** [Jude-Gideon/Blooket#18]
idk what happened, it worked perfectly fine and now it just doesnt

**Comment by Jude-Gideon** [comment]
It would be cool if I knew what hack you're claiming doesn't work..

**Comment by Jude-Gideon** [comment]
It would be cool if I knew what hack you're claiming doesn't work..

**Comment by Jude-Gideon** [comment]
Fixed get all blooks if that was it.
