### ISSUE TITLE
Multiplier Bonus View

### ISSUE THREAD

**Issue by notahumans-official** [Jude-Gideon/Blooket#20]
Can you make a cheat that allows me to see which bonus I will get if I click each one? I want to guarentee 3x bonus every time![image](https://user-images.githubusercontent.com/60613873/199282655-284b2cf8-1bf7-4a02-9786-996edd86466b.png)

**Comment by Jude-Gideon** [comment]
It's completely random, it's not possible I don't believe, it shouldn't matter if you just use addrewards because it gives you max daily xp and tokens.

**Comment by Jude-Gideon** [comment]
I may look into this in the future but not at this moment./
