### ISSUE TITLE
Hello mr new age glixzzy

### ISSUE THREAD

**Issue by InvertedBeans** [Jude-Gideon/Blooket#21]
You have one problem, your sell all blooks is broken, dont work, ive done the javascript: like i did with the spam open. Is it me being stupid or what? thx!, also u are big brain

**Comment by Jude-Gideon** [comment]
Let me go check it out and I'll let you know.

**Comment by Jude-Gideon** [comment]
Fixed.

**Comment by InvertedBeans** [comment]
Aight thx, also check ur bots hack, just checked and it didnt add the bots
