### ISSUE TITLE
The open packs

### ISSUE THREAD

**Issue by LightingBolts** [Jude-Gideon/Blooket#24]
can you please make it when we type which box and how many but dont tap the blue button it just opens the box in one sitting instead of pressing a bunch of buttons. Also update it. i also want a new hack where we can get the blooket luck if thats a thing

**Comment by Jude-Gideon** [comment]
You kind of have to go through the blue buttons, I'm not going to edit it. You can't do luck either, that involves Blookets actual hardcoded values.

**Comment by Jude-Gideon** [comment]
Sorry
