### ISSUE TITLE
"Add Rewards"

### ISSUE THREAD

**Issue by notahumans-official** [Jude-Gideon/Blooket#31]
The add rewards cheat is broken, it worked fine yesterday. Can you fix it?

**Comment by Jude-Gideon** [comment]
It works fine for me, make sure you're using the most updated version, and that you haven't just hit the daily cap.

**Comment by notahumans-official** [comment]
Alright thanks

**Comment by notahumans-official** [comment]
@Jude-Gideon I tried again, it still won't work...
