### ISSUE TITLE
Add xp and tokens and all blooks not perm does not work.

### ISSUE THREAD

**Issue by E3th** [Jude-Gideon/Blooket#36]
I have been doing hacks for a while, only really using Javascript. Today I was trying to save up for chrismas but when I used the add tokens stuff it did not work, in a live game and in the play screen. I then tried to do the all blooks and it did not work either. I noticed that when I did the add tokens it changed the font of the text for a milisecond, before going back to normal. I hope this gets fixed so I can you the hack for pack openings.

**Comment by notahumans-official** [comment]
Okay, I had this issue, but I solved it. Instead of using the search bar, right-click your screen and click INSPECT. Go to console and paste the code there, then hit enter. It should work now. Hope this helps!

**Comment by Jude-Gideon** [comment]
yeah, i always just use inspect.

**Comment by Jude-Gideon** [comment]
everything works and i actively test nothing is broken at this time just use console not URL bar!
