### ISSUE TITLE
Add rewards and blooks on school chromebooks...

### ISSUE THREAD

**Issue by E3th** [Jude-Gideon/Blooket#37]
On a previous issue I said, I said that the javascript in the search bar did not work. I do these hacks on a school chromebook... So I cannot inspect for it shows up but is like grey and I a unable to click it. So the only way I can use the hacks are by doing the search bar that does now not work... Can you please fix that and or tell me how I can disable the schools acess to those permissions and if you can do that will you also tell me how to put the schools permissions back on?

**Comment by Jude-Gideon** [comment]
ive never used a chromebook so i dont have much, try making a bookmark theres a dicussion on it

**Comment by 9217182672** [comment]
I have the same issue, I can't do inspect because I'm on a school Chromebook And as E3th said the search bar doesn't work it's okay if you can't do anything about it, I'm just pointing it out there

**Comment by E3th** [comment]
I did do the bookmarks, but I updated to your most updated one,... and it did not work. I tried the all blooks and add rewards in game and in the place where you put in the game pin. I hope you can fix this if you can.

**Comment by notahumans-official** [comment]
The only way is through the inspect console now. We chromebookers need some help :(

**Comment by notahumans-official** [comment]
Okay, I found our issue @Anoncog @E3th @9217182672 Go to chrome://policy on your chromebook. Check the blocked url list, if you see "javascript://*" all javascript links are auto-blocked!
