### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by prndndndndnndnd** [Jude-Gideon/Blooket#48]
can you make blooket api hacks

**Comment by Jude-Gideon** [comment]
Elaborate? That's what these are pretty much...?

**Comment by prndndndndnndnd** [comment]
like where you can get the toxen up upping the limit on the api on blooket for the server side

**Comment by Jude-Gideon** [comment]
No.

**Comment by notahumans-official** [comment]
You really can't do that. You'll get banned, they always find out...
