### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by Minesraft2** [Jude-Gideon/Blooket#51]
These are just cheats from https://github.com/therealgliz/blooket-hacks with a modified footer

**Comment by Minesraft2** [comment]
Scratch that, they're taken from https://github.com/rxzyx/Blooket-Hacks/, which also happens to be a skid

**Comment by Minesraft2** [comment]
AND you took the footer from gliz's code

**Comment by Jude-Gideon** [comment]
False issue 💀 Only thing I've used is the fake gliz's footer, all code is made by me.

**Comment by Jude-Gideon** [comment]
> These are just cheats from https://github.com/therealgliz/blooket-hacks with a modified footer

Plus, therealgliz is fake, test those hacks guarantee they don't work.

**Comment by Minesraft2** [comment]
False issue my ass, I compared the deobfuscated codes, you didn't even change the stateNode variable name

**Comment by Minesraft2** [comment]
> > These are just cheats from https://github.com/therealgliz/blooket-hacks with a modified footer
> 
> Plus, therealgliz is fake, test those hacks guarantee they don't work.

I recently discovered it was actually gliz, and he's working on getting the account back sinnce he used a proton email for it

**Comment by Jude-Gideon** [comment]
> False issue my ass, I compared the deobfuscated codes, you didn't even change the stateNode variable name

I don't have deobfuscated code available, theres no proof at all.

**Comment by Jude-Gideon** [comment]
Plus, throughout issues somehow I've fixed the hacks which is so crazy considering you think I stole code.

**Comment by Minesraft2** [comment]
Plus it looks like you just made a copy of the [Ben Stewart License](https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE) and modified it a bit

**Comment by Jude-Gideon** [comment]
> Plus it looks like you just made a copy of the [Ben Stewart License](https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE) and modified it a bit

Just because licenses are similar doesn't mean I stole it, I made a license protecting my code.

**Comment by Minesraft2** [comment]
![image](https://user-images.githubusercontent.com/49218878/204101292-74e73b27-7430-47db-a203-4d12a135d529.png)
This is a snip from your add crypto, 
![image](https://user-images.githubusercontent.com/49218878/204101306-ab59977a-288f-4927-bfb5-1faa2269e9c1.png)
and this is a snip from rxzyx's

**Comment by Minesraft2** [comment]
See the resemblence?

**Comment by Minesraft2** [comment]
![image](https://user-images.githubusercontent.com/49218878/204101365-2176cdbb-307c-48fa-bec8-7ef8040d9c49.png)
And the iframe stuff from the top is also the same

**Comment by Minesraft2** [comment]
Stealing code from rxzyx's repo and adding a footer also goes against his [license](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE) too

**Comment by Jude-Gideon** [comment]
LOL. that's not even deobfuscated code. just because its in shambles doesn't make it deobfuscated, I have all the source code on my computer.

**Comment by Minesraft2** [comment]
It _is_ the deobfuscated code using https://deobfuscate.relative.im/

**Comment by Minesraft2** [comment]
And incase you didn't know, gliz's footer was also made by me

**Comment by Jude-Gideon** [comment]
> Stealing code from rxzyx's repo and adding a footer also goes against his [license](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE) too

I told rxzyx to write that license yk 🤣

**Comment by Minesraft2** [comment]
> > Stealing code from rxzyx's repo and adding a footer also goes against his [license](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE) too
> 
> I told rxzyx to write that license yk 🤣


And it's good you did because now he has means to dmca yours

**Comment by Jude-Gideon** [comment]
> > > Stealing code from rxzyx's repo and adding a footer also goes against his [license](https://github.com/rxzyx/Blooket-Hacks/blob/main/LICENSE) too
> > 
> > I told rxzyx to write that license yk 🤣
> 
> 
> And it's good you did because now he has means to dmca yours

Go to his repo, find a hack, its funny how my code doesn't match his, a dmca wouldnt work 🤦‍♂️
