### ISSUE TITLE
Skid 2 electric boogaloo

### ISSUE THREAD

**Issue by Minesraft2** [Jude-Gideon/Blooket#52]
I compared another cheat like you asked and surprise surprise!
Yours
![image](https://user-images.githubusercontent.com/49218878/204101677-c6a8b105-4e1b-4948-8e00-8bf5ccd690b8.png)
rxzyx's
![image](https://user-images.githubusercontent.com/49218878/204101716-688d3ec6-f07e-46bf-856a-c6d591da11c9.png)

**Comment by GooseterV** [comment]
yeah this guy is literally just taking people's stuff and reuploading it as "his own which he made" even though the deobfusvated source code is the exact same with nothing changed...
