### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Joemamagangster** [Jude-Gideon/Blooket#55]
Using the dev console (Ctrl+shift+J) , can you reduce a packs cost to zero?

**Comment by Wilke000** [comment]
Nope! Thats server sided

**Comment by Joemamagangster** [comment]
So you cant edit it in any way shape or form? Or put code in to let you edit it?????

**Comment by Wilke000** [comment]
No. You can spam open packs tho.

**Comment by Wilke000** [comment]
Some people have made a simulate open which is just like a simulation of opening a blook. *Does not save blook
