### ISSUE TITLE
Tower Of Doom Max stats

### ISSUE THREAD

**Issue by TheR1000** [Jude-Gideon/Blooket#6]
When I win a battle, I can't select a card after.

**Comment by Jude-Gideon** [comment]
Hmm, what platform are you on? Works fine for me.

**Comment by Jude-Gideon** [comment]
![image](https://user-images.githubusercontent.com/113489420/197408815-28f8c23d-6d4a-448c-8302-3add9f8cebab.png)
I can still select cards after this.

**Comment by Jude-Gideon** [comment]
![image](https://user-images.githubusercontent.com/113489420/197408837-8a1bad63-674c-44e2-8303-9e10894ccea5.png)

**Comment by TheR1000** [comment]
I’m on Edge

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Jude-Gideon** [comment]
If you can try in another browser because I'm using Chrome and it works fine, maybe try keeping the console open, I don't think thats a issue but try.

**Comment by TheR1000** [comment]
I'm only on edge

**Comment by Jude-Gideon** [comment]
> I'm only on edge

Well. Try keeping the console open because it works fine for me, you can also try going in the url bar and typing javascript; then paste the hack after the : but it works for me so I'm going to go ahead and close this, reopen this if you need more help.
