### ISSUE TITLE
Request for Blook Opening

### ISSUE THREAD

**Issue by notahumans-official** [Jude-Gideon/Blooket#60]
Can you make a tool that lets me pick which blook I will get when I open a pack. (I WANT A SPECIAL SNOW GLOBE SO BAD!!!) This is so I won't have to worry about the book getting picked by someone else before I can insert the allBlooks hack and choose it. It will save time! Thanks

**Comment by Wilke000** [comment]
Nope! That’s server sided.

**Comment by Jude-Gideon** [comment]
What he said.

**Comment by notahumans-official** [comment]
Dang okay
