### ISSUE TITLE
doesnt atviate

### ISSUE THREAD

**Issue by prndndndndnndnd** [Jude-Gideon/Blooket#61]
it doesn't work when I put in into the console

**Comment by Wilke000** [comment]
Hit enter

**Comment by prndndndndnndnd** [comment]
i did that than it made a error

**Comment by Wilke000** [comment]
Which code are you using

**Comment by prndndndndnndnd** [comment]
the daliy tokens one

**Comment by Wilke000** [comment]
Are you using it on play.blooket.com

**Comment by prndndndndnndnd** [comment]
no when in marketplace and blooks page

**Comment by Wilke000** [comment]
Do it on play.blooket.com

**Comment by Jude-Gideon** [comment]
It should say to use it on play.blooket.com
