### ISSUE TITLE
the flood serve is slow and dosnet work.

### ISSUE THREAD

**Issue by JustMeGuy** [Jude-Gideon/Blooket#65]
i was trying to do 100 bots and it only did 20 and it goose quite slow i normally use mincraft 2s but im testin ou new hacks

**Comment by Glixh** [comment]
Maybe your computer/phone is slow and his script is fine? Ever think of that?

**Comment by Jude-Gideon** [comment]
> i was trying to do 100 bots and it only did 20 and it goose quite slow i normally use mincraft 2s but im testin ou new hacks

Hmm, works for me it usually depends on your wifi network.

**Comment by Jude-Gideon** [comment]
It also depends on how many people are in the lobby, Blooket can only have so many people per lobby.
