### ISSUE TITLE
i dont have a persanal computer

### ISSUE THREAD

**Issue by y47dewsy** [Jude-Gideon/Blooket#73]
chrome store and inspect is not avalible for on a school computer and i dont have my very own that i own how do i use these?

**Comment by Wilke000** [comment]
Bookmarklets

**Comment by Jude-Gideon** [comment]
Push CTRL shift and J and paste the code

**Comment by Jude-Gideon** [comment]
Bookmark the code and use it that way

**Comment by y47dewsy** [comment]
thank you

**Comment by y47dewsy** [comment]
> Bookmark the code and use it that way
i try that but once my courser goes near the bookmark it freezes for a few seconds anyother ways?

**Comment by Jude-Gideon** [comment]
> > Bookmark the code and use it that way
> > i try that but once my courser goes near the bookmark it freezes for a few seconds anyother ways?

They probably just block it then.

**Comment by y47dewsy** [comment]
> > > Bookmark the code and use it that way
> > > i try that but once my courser goes near the bookmark it freezes for a few seconds anyother ways?
> 
> They probably just block it then.

ok thx for the help ur hacks have been working for me when i get access to a pc in school
