### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by UmbraAstro** [Jude-Gideon/Blooket#79]
Can you make a gui?

**Comment by Jude-Gideon** [comment]
There already is one?

**Comment by Jude-Gideon** [comment]
https://github.com/Jude-Gideon/Blooket/blob/main/Global/gui.js

**Comment by Jude-Gideon** [comment]
lmk if there are any errors

**Comment by Jude-Gideon** [comment]
it should work

**Comment by Jude-Gideon** [comment]
lmk of any errors
